
[nginx]
172.31.27.237 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa.pem

[db]
172.31.22.135 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa.pem