[tooling]
<Tooling-Web-Server-Private-IP-Address>

[todo]
<Todo-Web-Server-Private-IP-Address>

[nginx]
172.31.17.23 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa.pem

[db:vars]
ansible_user=ec2-user
ansible_python_interpreter=/usr/bin/python

[db]
172.31.2.31 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa.pem