pipeline{
   agent any

   environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

     parameters {
      string(name: 'inventory_file', defaultValue: '${inventory}',  description: 'selecting the environment')
          }
     

   stages{

      stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }

      stage('Checkout SCM') {
         steps{
            git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/tobesegun/ansible-config-mgt.git'
         }
       }
      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}'
          sh 'sed -i "3 a roles_path = ${WORKSPACE}/roles"  ${WORKSPACE}/deploy/ansible.cfg'
          
        }
      }


      stage('Run Ansible') {
        steps {
            ansiblePlaybook become: true, colorized: true, credentialsId: 'privatekey', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml'
        }
      }

      stage('Clean Workspace after build'){
        steps{
          cleanWs()
        }
      }
   }   
}  